name: Build and Upload Raylib WebAssembly Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        choco install cmake ninja -y
        choco install mingw -y
        choco install git -y
        choco install python -y
        choco install emscripten -y

    - name: Compile Raylib for Web
      env:
        EMSCRIPTEN_CMAKE_TOOLCHAIN_FILE: ${{ env.EMSDK_CMAKE_TOOLCHAIN_FILE }}
      run: |
        # Ensure the build directory is clean
        if exist build (rmdir /s /q build)
        
        # Create the build directory
        mkdir build
        cd build
        
        # Generate CMake files
        emcmake cmake ..
        
        # Build the project
        cmake --build .
        
        # Navigate back to the root directory
        cd ..

    - name: Package Web Build into Zip
      run: |
        # Navigate to the build directory
        cd build
        
        # Create a zip package of the HTML, wasm, and JS files
        Compress-Archive -Path index.html,*.wasm,*.js -DestinationPath raylib_web_game.zip

    - name: Upload Web Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: raylib_web_game
        path: build/raylib_web_game.zip