name: Build and Upload Raylib WebAssembly Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Emscripten SDK
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest

    - name: Install Dependencies
      run: sudo apt-get install -y ibasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev libxinerama libxinerama cmake make wayland-protocols libwayland-dev libxkbcommon-dev libglfw3-dev


    - name: Compile Raylib for Web
      run: |
        # Ensure the build directory is clean
        rm -rf build
        
        # Create the build directory
        #mkdir -p build
        cmake -S . -B build
        #cmake --build build

        # Navigate to the src directory (this assumes main.c is in the src folder)
        
        
        ls -R
        # Compile using emcc with WebAssembly flags
        emcc main.c -o ../build/index.html -s USE_GLFW=3 -s WASM=1 --shell-file ../shell.html -Os -Wall

    - name: Package Web Build into Zip
      run: |
        # Navigate to the build directory
        cd build
        
        # Create a zip package of the HTML, wasm, and JS files
        zip -r raylib_web_game.zip index.html *.wasm *.js

    - name: Upload Web Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: raylib_web_game
        path: build/raylib_web_game.zip
