name: Build and Upload Raylib WebAssembly Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        # Update and install essential build tools
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build git python3 wget unzip

        # Install Wayland and XKB dependencies (in case they're needed, but can be skipped for WebAssembly)
        sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev libx11-dev libegl1-mesa-dev

    - name: Install Emscripten
      run: |
        echo "Installing Emscripten..."
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk

        # Fetch and install the latest Emscripten SDK
        ./emsdk install latest

        # Activate the latest Emscripten SDK
        ./emsdk activate latest

        # Source the Emscripten environment variables
        source ./emsdk_env.sh

        # Save environment variables for later steps
        echo "EMSDK_PATH=$(pwd)" >> $GITHUB_ENV
        echo "source $EMSDK_PATH/emsdk_env.sh" >> $GITHUB_ENV

    - name: Configure and Build Raylib WebAssembly Game
      run: |
        # Load Emscripten environment
        source $GITHUB_ENV

        # Ensure the build directory is clean
        rm -rf build
        mkdir build
        cd build

        # Run the CMake configuration for WebAssembly (PLATFORM_WEB)
        emcmake cmake -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release ..

        # Build the project using emmake
        emmake make

    - name: Package Web Build into Zip
      run: |
        # Load Emscripten environment
        source $GITHUB_ENV

        # Package the build into a zip file
        cp my_game.html index.html
        zip raylib_web_game.zip *.html *.wasm *.js

    - name: Upload Web Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: raylib_web_game
        path: build/raylib_web_game.zip
